[package]
name = "exex-mev-inspect"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
reth-ethereum = { workspace = true, features = ["full", "cli"] }
reth-exex-mev.workspace = true

eyre.workspace = true
futures.workspace = true
tracing.workspace = true
